javascript_whitelist = [
    'https://soundcloud.com',
    'https://duckduckgo.com',
    'https://mullvad.net',
    'https://ethermine.org',
    'https://www.youtube.com',
    'https://docs.invidious.io',
    'https://peer.tube',
    'https://www.protondb.com',
    'https://tube.netzspielplatz.de',
    'https://joinpeertube.org',
    'https://peertube.co.uk',
    'https://mail.protonmail.com',
    'https://mastodon.social',
    'https://www.redditp.com',
]
