def bind(config):
    config.unbind('J', mode='normal')
    config.unbind('K', mode='normal')
    config.unbind('d', mode='normal')
    config.unbind('th', mode='normal')
    config.unbind('tl', mode='normal')
    config.unbind('?', mode='normal')
    config.unbind(';t', mode='normal')

    config.bind('<Shift-i>', 'config-source')
    config.bind('x', 'tab-close')
    config.bind('J', 'tab-prev')
    config.bind('K', 'tab-next')
    config.bind('gh', 'back -t')
    config.bind('gl', 'forward -t')
    config.bind('t', 'tab-clone')
    config.bind('?', 'open -t qute://help/img/cheatsheet-big.png')
    config.bind(',s', 'open -t qute://settings')
    config.bind(';t', 'hint links spawn transmission-remote -a {hint-url}')

    config.bind('dy', 'open youtube.com')
    config.bind('dr', 'open reddit.com')
    config.bind('dm', 'open protonmail.com')
    config.bind('dg', 'open gmail.com')
    config.bind('df', 'open facebook.com')

    config.bind('dY', 'open -t youtube.com')
    config.bind('dR', 'open -t reddit.com')
    config.bind('dM', 'open -t protonmail.com')
    config.bind('dG', 'open -t gmail.com')
    config.bind('dF', 'open -t facebook.com')

    config.bind('dl', 'spawn smplayer {url}')
    config.bind('dL', 'spawn youtube-dl {url}')
