def bind(config):
    config.unbind('J', mode='normal')
    config.unbind('K', mode='normal')
    config.unbind('H', mode='normal')
    config.unbind('L', mode='normal')
    config.unbind('d', mode='normal')
    config.unbind('th', mode='normal')
    config.unbind('tl', mode='normal')
    config.unbind('?', mode='normal')
    config.unbind(';t', mode='normal')
    config.unbind(';t', mode='normal')

    config.bind('I', 'config-source')
    config.bind('x', 'tab-close')
    config.bind('J', 'tab-prev')
    config.bind('K', 'tab-next')
    config.bind('h', 'back')
    config.bind('l', 'forward')
    config.bind('H', 'back -t')
    config.bind('L', 'forward -t')
    config.bind('t', 'open -t duckduckgo.com')
    config.bind('?', 'open -t qute://help/img/cheatsheet-big.png')

    navbind('y', 'youtube.com', config)
    navbind('a', 'archlinux.org', config)
    navbind('r', 'reddit.com', config)
    navbind('m', 'protonmail.com/login', config)
    navbind('g', 'gmail.com', config)
    navbind('f', 'facebook.com', config)
    navbind('s', 'soundcloud.com', config)

    config.bind(',s', 'open -t qute://settings')
    config.bind(',dt', 'hint links spawn transmission-remote -a {hint-url}')
    config.bind(',dd', 'hint links spawn youtube-dl -r 800k -o "~/Downloads/%(title)s.%(ext)s" {hint-url}')
    config.bind(',dD', 'spawn youtube-dl -r 800k -o "~/Downloads/%(title)s.%(ext)s" {url}')
    config.bind(',da', 'hint links spawn youtube-dl -r 800k -f bestaudio -o "~/Downloads/%(title)s.%(ext)s" -x --audio-format opus --audio-quality 0 {hint-url}')
    config.bind(',dA', 'spawn youtube-dl -r 800k -f bestaudio -o "~/Downloads/%(title)s.%(ext)s" -x --audio-format opus --audio-quality 0 {url}')
    config.bind(',e', ':spawn --userscript emacspaste')

def navbind(bind, link, config):
    config.bind('d' + bind, 'open ' + link)
    config.bind('d' + bind.upper(), 'open -t ' + link)
