def bind(config):
    config.unbind('J',  mode='normal')
    config.unbind('K',  mode='normal')
    config.unbind('H',  mode='normal')
    config.unbind('L',  mode='normal')
    config.unbind('d',  mode='normal')
    config.unbind('th', mode='normal')
    config.unbind('tl', mode='normal')
    config.unbind('?',  mode='normal')
    config.unbind(';t', mode='normal')
    config.unbind(';t', mode='normal')

    config.bind('I', 'config-source')
    config.bind('x', 'tab-close')
    config.bind('J', 'tab-prev')
    config.bind('K', 'tab-next')
    config.bind('h', 'back')
    config.bind('l', 'forward')
    config.bind('H', 'back -t')
    config.bind('L', 'forward -t')
    config.bind('t', 'open -t duckduckgo.com')
    config.bind('?', 'open -t qute://help/img/cheatsheet-big.png')

    config.bind('<Ctrl-J>', 'scroll-page 0 0.5')
    config.bind('<Ctrl-K>', 'scroll-page 0 -0.5')

    navbind('y', 'https://youtube.com',                 config)
    navbind('a', 'https://archlinux.org',               config)
    navbind('e', 'https://ebay.com',                    config)
    navbind('r', 'https://reddit.com',                  config)
    navbind('m', 'https://protonmail.com/login',        config)
    navbind('g', 'https://gmail.com',                   config)
    navbind('f', 'https://facebook.com',                config)
    navbind('s', 'https://soundcloud.com',              config)
    navbind('i', 'https://discordapp.com/channels/@me', config)
    navbind('b', 'https://bitbucket.org', config)

    config.bind('dnm', 'open -t ' + 'https://moss-avis.no')
    config.bind('dna', 'open -t ' + 'https://www.aftenposten.no/')
    config.bind('dnv', 'open -t ' + 'https://www.vg.no/')

    config.bind(',s',  'open -t qute://settings')
    config.bind(',dm', 'hint links spawn mpv {hint-url} --no-video')
    config.bind(',dt', 'hint links spawn transmission-remote -a {hint-url}')
    config.bind(',dd', 'hint links spawn youtube-dl -r 800k -o "~/Downloads/%(title)s.%(ext)s" {hint-url}')
    config.bind(',dD', 'spawn youtube-dl -r 800k -o "~/Downloads/%(title)s.%(ext)s" {url}')
    config.bind(',da', 'hint links spawn youtube-dl -r 800k -f bestaudio -o "~/Downloads/%(title)s.%(ext)s" -x --audio-format opus --audio-quality 0 {hint-url}')
    config.bind(',dA', 'spawn youtube-dl -r 800k -f bestaudio -o "~/Downloads/%(title)s.%(ext)s" -x --audio-format opus --audio-quality 0 {url}')
    config.bind(',D',  'download')
    config.bind(',e',  'spawn --userscript emacspaste')
    config.bind(',p',  'tab-pin')


def navbind(bind, link, config):
    config.bind('d' + bind,         'open ' + link)
    config.bind('d' + bind.upper(), 'open -t ' + link)
